# Generated by Django 3.2.17 on 2023-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField(unique=True)),
                ('Employee_FirstName', models.CharField(max_length=100)),
                ('Employee_MiddleName', models.CharField(max_length=100)),
                ('Employee_LastName', models.CharField(max_length=100)),
                ('Employee_Department', models.CharField(max_length=64)),
                ('Employee_Designation', models.CharField(max_length=64)),
                ('Employee_CTC', models.FloatField()),
                ('Employee_Salary', models.FloatField()),
                ('Employee_Date_of_joined', models.DateField()),
            ],
        ),
    ]
