# Generated by Django 3.2.17 on 2023-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField(unique=True)),
                ('Employee_FirstName', models.CharField(max_length=100)),
                ('Employee_MiddleName', models.CharField(max_length=100)),
                ('Employee_LastName', models.CharField(max_length=100)),
                ('Employee_Department', models.CharField(max_length=64)),
                ('Employee_Designation', models.CharField(max_length=64)),
                ('Employee_Date_of_joined', models.DateField()),
                ('Employee_Bank_Name', models.CharField(max_length=64, null=True)),
                ('Employee_Bank_Account_Number', models.IntegerField(null=True)),
                ('Employe_Bank_IFSC_Code', models.CharField(max_length=64, null=True)),
                ('Employee_Pan_Number', models.CharField(max_length=64, null=True)),
                ('Employee_UAN_Number', models.IntegerField(default=True)),
                ('Employee_PF_Number', models.CharField(max_length=64, null=True)),
                ('Employee_ESI_Number', models.IntegerField(null=True)),
                ('Employee_Actual_Payable_Days', models.FloatField(null=True)),
                ('Employee_Total_Working_Days', models.FloatField(null=True)),
                ('Employee_Loss_Of_Pay_Days', models.FloatField(default=True)),
                ('Employee_Paid_Leaves', models.FloatField()),
                ('Employee_Basic', models.FloatField()),
                ('Employee_Conveyance_Allowance', models.FloatField()),
                ('Employee_HRA', models.FloatField()),
                ('Employee_Medical_Allowance', models.FloatField()),
                ('Employee_Special_Allowance', models.FloatField()),
                ('Employee_Variable_Pay', models.FloatField()),
                ('Employee_Total_Earnings', models.FloatField()),
                ('Employee_PF_Employee', models.FloatField()),
                ('Employee_PF_Employer', models.FloatField()),
                ('Employee_ESI_Employee', models.FloatField(null=True)),
                ('Employee_ESI_Employer', models.FloatField()),
                ('Employee_Total_Contributions', models.FloatField()),
                ('Employee_Professional_Tax', models.FloatField()),
                ('Employee_Total_Deductions', models.FloatField()),
                ('Employee_Net_Salary', models.FloatField()),
                ('Employee_Salary_Month_and_Year', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Bank_Account_Number',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Bank_IFSC_Code',
            field=models.CharField(default=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Bank_Name',
            field=models.CharField(default=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_ESI_Number',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_PF_Number',
            field=models.CharField(default=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Pan_Number',
            field=models.CharField(default=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Profile_Photo',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Sub_Department',
            field=models.CharField(default=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_UAN_Number',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_CTC',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Salary',
            field=models.FloatField(null=True),
        ),
    ]
