# Generated by Django 3.2.17 on 2023-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0003_alter_employeedata_employee_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Bank_Account_Number',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Bank_IFSC_Code',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Bank_Name',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Department',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Designation',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_ESI_Number',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_PF_Number',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Pan_Number',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Profile_Photo',
            field=models.ImageField(default='', null=True, upload_to='Employee_data/media'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_Sub_Department',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Employee_UAN_Number',
            field=models.IntegerField(default='', null=True),
        ),
    ]
