# Generated by Django 3.2.17 on 2023-02-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0004_auto_20230216_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='Employee_Profile_Photo',
        ),
    ]
