# Generated by Django 3.2.17 on 2023-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0005_remove_employeedata_employee_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('Date', models.DateField()),
                ('billNo', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('bill_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='Employee_Salary',
            field=models.FloatField(null=True),
        ),
    ]
