# Generated by Django 3.2.17 on 2023-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0006_auto_20230228_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Profile_Photo',
            field=models.ImageField(default='', null=True, upload_to='Employee_Photo'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bill_image',
            field=models.FileField(upload_to='Expenses'),
        ),
    ]
